name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install project dependencies
        run: npm ci

      - name: Run unit test with vitest
        run: npm run test:unit

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: vitest-report
          path: vitest-report/
          retention-days: 30

  e2e:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install project dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Build artifacts
        run: npm run build

      - name: Start background service
        run: npm run preview &

      - name: Run e2e test with Playwright
        run: npm run test:e2e

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
